export const skills = [
  "Html",
  "Css",
  "JavaScript",
  "GitHub",
  "JSX",
  "React",
  "React Router",
  "Hooks",
  "Styled Components",
  "Api",
  "Axios",
  "Redux",
  "Redux Toolkit",
  "npm",
  "json",
  "Scrum",
  "Team Work",
  "Pull requests",
  "Review in GitHub",
  "Responsiveness",
  "Figma",
  "Trello",
];

export const nextSkills = [
  "typeScript",
  "AI",
  "SQL",
  "Next.js",
  "More about npm",
  "More about json",
  "More about team work",
  "More about Scrum",
  "More about Pull requests",
  "More about review",
];